# Generated by Django 5.2 on 2025-05-06 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_suggestedquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Дүйсенбі', 'Дүйсенбі'), ('Сейсенбі', 'Сейсенбі'), ('Сәрсенбі', 'Сәрсенбі'), ('Бейсенбі', 'Бейсенбі'), ('Жұма', 'Жұма'), ('Сенбі', 'Сенбі')], max_length=10)),
                ('time', models.TimeField()),
                ('subject', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
